name: Build Archlinux with kupferbootstrap for oneplus-fajita
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_flavour:
        description: "flavour"
        required: true
        default: "phosh"
  
env:
  TZ: Asia/Shanghai

jobs:
  aarch64_job:
    # The host should always be Linux
    runs-on: ubuntu-20.04
    name: Build on ubuntu-20.04 aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: archarm_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            pacman -Sy
            groupadd docker
            pacman -S python docker glibc shadow docker-buildx git --needed --noconfirm
            usermod -aG docker "$(whoami)"
            git clone -b dev https://gitlab.com/kupfer/kupferbootstrap
            cd kupferbootstrap
            pip3 install -r requirements.txt
            ln -s "$(pwd)/bin/kupferbootstrap" /usr/local/bin/
            kupferbootstrap -V

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
